---
openapi: 3.0.1
info:
  title: Kong Gate Way Test Api
  description: REST API as Kong test.
  #termsOfService: http://localhost:/terms-and-conditions/
  contact:
    email: help@test.com
  version: '1.0'
servers:
- url: https://localhost:44337
  description: Local environment
tags:
  - name: WeatherForecast
paths:
  "/WeatherForecast":
    get:
      tags: 
        - WeatherForecast
      operationId: WeatherForecast-get
      description: Return list of weather forecast.
      summary: Return list of weather forecast.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/WeatherForecast"
components:
  schemas:
    WeatherForecast:
        type: object
        properties:
            Summary:
                type: string
                nullable: true
            TemperatureF: 
                type: integer
                format: int32
            TemperatureC:
                type: integer
                format: int32
            Date: 
                type: string
                format: date-time
        additionalProperties: false
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-KEY
      in: header
    apiKeyId:
      type: apiKey
      name: X-API-KEY-ID
      in: header
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
security:
- bearerAuth: []
  apiKey: []
  apiKeyId: []      